name = "Migajaland"
author = "Migajaland"
version = "0.6.6-rc4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2df27376b52fd6658fdc29b349129b731115811971a75ebfeb01a6a18912d22"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"