name = "Migajaland"
author = "Migajaland"
version = "0.6.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47e9c2b3c72785eac79eae61f7912c6a993d6e30e2d7ab06abbdca962477f784"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"