name = "Migajaland"
author = "Migajaland"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1cc35e75fd6514a4711aed081372589f11868516ebb7ae64cbaf30ce8dd31b8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"